### ISSUE TITLE
Optimise the code

### ISSUE THREAD

**Issue by pandeyganesha** [pandeyganesha/n-queen#1]
The code is written in such a way that we get our solution while ignoring the time complexities. Please contribute if you could help in reducing the time complexity by changing the code (Not the algo).

**Comment by Mr-G-D** [comment]
Hi @Ganesh910 , 
I would like to work on this task

**Comment by pandeyganesha** [comment]
@Mr-G-D Go ahead.

**Comment by Mr-G-D** [comment]
@Ganesh910 Assign it to me

**Comment by pandeyganesha** [comment]
@Mr-G-D 
Assigned it to you. You could have contributed even if you are not assigned :)
